global using IoTDeviceDataIngestor.IngestionService.Utilities;
global using IoTDeviceDataIngestor.IngestionService.Utilities.Exceptions;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using RabbitMQ.Client;
global using System.ComponentModel.DataAnnotations;
global using System.Text;
